FROM alpine:latest

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \ 
	&& apk update \
	&& apk add websockify 

RUN adduser -D -H gecoshc

USER gecoshc

CMD ["/usr/bin/websockify", "0.0.0.0:6900", "gecoshc_repeater:5900"]

